### ISSUE TITLE
use and meaning of NNUE files

### ISSUE THREAD

**Issue by tissatussa** [Matthies/NN#1]
hi, i find 4 NNUE files at https://github.com/Matthies/NN/ .. can they be used with other engines also?  So, are they "general" NNUE files or typical for RubiChess only?  Their size is about 112 Kb, which seems small to me .. most NNUE files i find on the internet are about 20 Mb .. the readme text has some explanation, but what can we expect regarding playing style and strength?  Can something be said about that?  The difference between NN files is vague to me (and other users, i guess).

**Comment by Matthies** [comment]
The network files are standard 20MB files and should be usable in other engines with "standard" NNUE implementation. No idea what went wrong when you only get 112kB.
Style and strength... well.. I only upload network files that are generated with Rubi training data and newer/younger nets are usually stronger than older ones. They are weaker than SF nets but I never compared them directly with nets of other engines.

**Comment by tissatussa** [comment]
> The network files are standard 20MB files and should be usable in other engines with "standard" NNUE implementation. No idea what went wrong when you only get 112kB.

i get a file of about 112 KB when doing "Save link as", eg. the 3rd nnue file https://github.com/Matthies/NN/blob/main/nn-cf8c56d366-20210326.nnue .. but i was wrong : i should have clicked the link and on that following HTML page click the 'download' button .. sorry, now i have the 20MB file !

> ... I never compared them directly with nets of other engines...

how can we compare NNUE files ?  Do test positions exist, eg. which have a clear "best move" ?

**Comment by Matthies** [comment]
> how can we compare NNUE files ? Do test positions exist, eg. which have a clear "best move" ?

Rebel has some position sets and a framework that uses this metric iirc: http://rebel13.nl/home/nnue.html
I would just play many test games EngineA_with_NetX vs EngineA_with_NetY.
But it is not that easy. The net is not totally independent from the engine. E.g. by tuning a scaling factor in my engines that fits best to my latest net I got > 10 Elo. The same scaling factor is probably not optimal for another net.

But I'm pretty sure even with a non-optimal scaling factor we would get
Rubi_with_SFnet > Rubi_with_RubiNet
and of course also
SF_with_SFnet > SF_with_RubiNet
